name: Hal
favicon: null
layout_spectrum: 0.12827
typography_spectrum: 0.55196
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#807f84'
    - '#0c0b07'
    - '#b3c4c8'
    - '#f6553a'
    - '#f79e3a'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
