name: Hal
favicon: null
layout_spectrum: 0.34062874456867576
typography_spectrum: 0.7759928095620126
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#807f84'
    - '#0c0b07'
    - '#b3c4c8'
    - '#f6553a'
    - '#f79e3a'
  brandStrength: 0.8864417769946158
  lightness: 0.4833982912823558
  saturation: 0.0912526142783463
  rhythmicContrast: 0.6649852490518242
purpose: []
