typography_spectrum: 0.55196
color:
  brandColors:
    - '#807f84'
    - '#0c0b07'
    - '#b3c4c8'
    - '#f6553a'
    - '#f79e3a'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.12827
analytics:
  google: null
  facebook: null
  twitter: null
name: Hal
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
